spring:
  datasource:
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapperLocations: classpath:com.lt.springboot.springbootnatis.mapper/*.xml
#
#resources: # 指定静态资源的路径
#  static-locations: classpath:/
#  cache-period: 0